### ISSUE TITLE
No more editor

### ISSUE THREAD

**Issue by tonioo** [django-blog-zinnia/cmsplugin-zinnia#37]
Hi,

after an update to django-cms 3.0.6, the HTML editor is not loading anymore when I create/update an entry. I just see raw HTML in a textarea.

My versions :
- django-cms 3.0.6
- zinnia 0.14.2
- cmsplugin-zinnia 0.6
- djangocms-text-ckeditor 2.4.1

Any idea?

PS: I was not sure about where to create this issue...

**Comment by bittner** [comment]
Related sections in the documentation:

* [Changelog for 0.14.2](http://docs.django-blog-zinnia.com/en/develop/notes/changelog.html#id4)
* [Ecosystem](http://docs.django-blog-zinnia.com/en/develop/topics/ecosystem.html#zinnia-wysiwyg-wymeditor) (zinnia-wysiwyg-* extensions)
