### ISSUE TITLE
NoReverseMatch Error When Accessing App Hook

### ISSUE THREAD

**Issue by freckles-the-pirate** [django-blog-zinnia/cmsplugin-zinnia#44]
When I navigate to a page with a cmsplugin-zinnia app_hoook the following error
is returned:

    NoReverseMatch at /blog/

    u'zinnia' is not a registered namespace

    Request Method: 	GET
    Request URL: 	    http://127.0.0.1:8000/blog/
    Django Version: 	1.7.4
    Exception Type: 	NoReverseMatch
    Exception Value:    u'zinnia' is not a registered namespace
    
    In template <home>/django-blog-zinnia/zinnia/templates/zinnia/tags/
    categories.html, error at line 5
    
    ...
    
 	{% load i18n %}
    <ul class="{% if not categories %}no-{% endif %}categories">
    {% for category in categories %}
        <li{% if category.slug == context_category.slug %} class="current"{% endif %}>
            <a href="{{ category.get_absolute_url }}"
            title="{% blocktrans %}Show all entries in {{ category }}{% endblocktrans %}">{{ category }}</a>
        {% blocktrans count entry_count=category.count_entries_published %}{{ entry_count }} entry{% plural %}{{ entry_count }} entries{% endblocktrans %}
        </li>
        {% empty %}
            <li>
                {% trans "No categories yet." %}
            </li>
    {% endfor %}
    </ul>
    
My system has the following setup:

* django-blog-zinnia==0.15.1
* django-cms==3.0.9
* djangocms-installer==0.7.2
* cmsplugin-zinnia==0.7

I installed DjangoCMS with djangocms-installer, installed zinnia, set up
django-blog-zinnia as per the README, and set up cmsplugin-zinnia as per the
README, paying close attention to do the following:

1. Keep the zinnia URL in my main urls.

        url(r'^weblog/', include('zinnia.urls', namespace='zinnia'))

2. Add a cms page with the slug 'blog' 
3. Create a category and entry. Publish the category and entry.
3. On the "blog" page, add the app hook "Published Categories"
4. Published categories are listed.
5. Once the app hook is added, remove the zinnia URL from my main urls
6. Restart the server.
7. Navigate to the '/blog/' page. The error occurs.

If I leave the zinnia url in my main urls the '/blog/' page does render, but
when I navigate to one of the categories, django can't resolve the URL (as the
documentation states).

Any ideas? Thanks.

**Comment by freckles-the-pirate** [comment]
Ah, I think I figured it out. I'll post the solution for those who were also confused.

On your blog page in the DjangoCMS Menu go to **Page > Advanced Settings.** For **Application** select **Zinnia Blog**. For **Application Instance Name**, make sure it says *zinnia*. Click **Save**.

**Comment by bittner** [comment]
Also note that you need to have the CMS page _published_ in order to make this error go away. (I had this problem.)

A freshly created page with an Apphock configured will still display a `NoReverseMatch Error` when not published. This is mentioned - implicitly regarding this problem - in the [django CMS docs](http://docs.django-cms.org/en/release-3.4.x/how_to/apphooks.html#using-an-apphook).
