### ISSUE TITLE
Tighter integration with django CMS 3 for front-end editing with EntryPlaceholder

### ISSUE THREAD

**Issue by bittner** [django-blog-zinnia/cmsplugin-zinnia#48]
Since django-CMS 3.0 it is not possible anymore to edit django-CMS placeholders in the Admin. Editing blog entries is now a mixture of backend and frontend editing when the `EntryPlaceholder` is used (see #39 for details on editing).
## Proposed Solution

When cmsplugin_zinnia is used with the `EntryPlaceholder` adding and editing blog posts should be fully possible from the frontend. User interaction should mimic django CMS 3's frontend editing closely.
1. _Zinnia_ > _New Entry ..._ (from the django CMS toolbar), which opens the Admin in the sidebar, may offer the _Excerpt_ plain text box in addition to _Title_, _Status_ and _Image_.
2. When the new blog entry is saved a django-CMS Text plugin should be created as the first, default placeholder automatically. This placeholder should be pre-filled with the text entered in the _Excerpt_ text box.
3. The newly created blog entry should be show on the website and suggest to continue editing. Alternatively, a list of all entries (the blog index) could be shown, and we scroll to the newly created entry.
4. The _Status_ may correspond to statuses of django CMS as follows:
   1. blog entries with "draft" status are visible and editable only when django CMS 3's edit slider is set to "draft".
   2. blog entries with "hidden" status are visible and editable only when django CMS 3's edit slider is set to "draft".
   3. only blog entries with "published" status are visible when django CMS 3's edit slider is set to "live".
5. All other data (Publication, Discussion, Privacy, etc.) should possibly be editable through double-clicking somewhere on a blog entry on the frontend. A modal popup window (layer) should be shown to edit the related data (similar to editing placeholders).
## Align draft/publish with django CMS

An additional enhancement would be to have a real "draft" version of blog posts, which can be edited and saved without immediately propagating to the published website. As a result, the Zinnia blog and django CMS would both follow the same draft/publish paradigma from a user experience point of view.

**Comment by jdejoode** [comment]
I agree that this would be a valuable addition.

**Comment by jdejoode** [comment]
@bittner Did you do any work on this? At present, I think django cms + zinnia (and EntryPlaceholder) is really weird.

**Comment by bittner** [comment]
@jdejoode I'll be certainly working on this in the next few weeks, could be getting November though. I need this to work seamlessly from a user perspective (100% from the frontend), but I have other tasks in my queue before that, unfortunately (for this bug).

**Comment by bittner** [comment]
I've started an Open Source kickstarter campain, [issue #755](https://freedomsponsors.org/issue/755/tighter-integration-with-django-cms-3-for-front-end-editing-with-entryplaceholder) at freedomsponsors.org. I hope that's fine for everyone.

Anyone interested in this feature is welcome to offer some incentives for anyone willing to implement what we ask for. That may make it more probable that an implementation happens in near future.

**Comment by bittner** [comment]
If it's just about adding a blog entry from the front-end, this is relatively easy to do with django CMS 3.2's content creation wizards (screenshot below is fake, don't worry).

[![Everything Is AWESOME](http://i.imgur.com/Ot5DWAW.png)](https://www.youtube.com/watch?v=HFcoSPqgbOE&t=5m40s)

The details of the implementation are demoed starting at [minute 11 in the video](https://www.youtube.com/watch?v=HFcoSPqgbOE&t=11m20s). The first 3 bullets from [my specification above](#issue-72296911) should be feasible to implement this way. Not *no* work but a feasible effort.

Anyone willing to try this out? -- If not, I may give this a shot in a few weeks time.
