### ISSUE TITLE
Release to remove Django check warnings

### ISSUE THREAD

**Issue by evenicoulddoit** [django-blog-zinnia/cmsplugin-zinnia#53]
I went to fix the check warnings raised by Django, only to notice that they've actually already been fixed in the develop branch. Are there any plans to bump the version so that I can get rid of the warnings?

**Comment by bittner** [comment]
:+1:  Would be nice.

**Comment by dholbach** [comment]
:+1:  Agreed. :-)

**Comment by bittner** [comment]
@Fantomas42 Any hope, Julien, this is going to happen any time soon?

**Comment by npardington** [comment]
I ended up putting this in my requirements to use it in Django 1.9 but I agree a release would be much appreciated.

`git+git://github.com/django-blog-zinnia/cmsplugin-zinnia.git@ed319b4959cab3066fda2a56bbd85733caf47033`

Thanks for your work @Fantomas42

**Comment by Fantomas42** [comment]
Hello,

I have just released the v0.8.1 of cmsplugin-zinnia on Pypi.

Sorry for the late release.

Regards
